### ISSUE TITLE
[Info] No licenses found for ...

### ISSUE THREAD

**Issue by Janpopan** [porscheinformatik/sonarqube-licensecheck#103]
This info is completly ignored in the report an at the ui:

[Info] 18:30:53.575 No licenses found for 'Indiana University Extreme! Lab Software License, vesion 1.1.1'
[Info] 18:30:53.590 No licenses found for 'Public Domain'

right?

So what happend with this pakages? There is nothing in the ui.

My testcase ist the software itself.

**Comment by derkoe** [comment]
This happens when no license mapping can be found for a given license entry in a POM-file. In this case xpp3 has 3 licenses defined - one (Apache 1.1) is mapped per default. The others fail to map.

When no license can be mapped  - it shows up as unknown license and raises an issue.
