### ISSUE TITLE
Connect GitHubRepo with SonarCloud / SonarCloud Code Analysis

### ISSUE THREAD

**Issue by Janpopan** [porscheinformatik/sonarqube-licensecheck#105]
It is a sonar plugin so let the code check with the github sonarcloud app

**Comment by derkoe** [comment]
Project already analyzed with sonarcloud: https://sonarcloud.io/dashboard?id=at.porscheinformatik.sonarqube.licensecheck%3Asonarqube-licensecheck-plugin

**Comment by Janpopan** [comment]
Will you add a sonarcloud badge to readme.md ?
