### ISSUE TITLE
IllegalStateException: The web service 'api/licenses' is defined multiple times

### ISSUE THREAD

**Issue by csetera** [porscheinformatik/sonarqube-licensecheck#11]
I have recently set up a new Sonarqube instance and was excited to install the license check plugin for Sonarqube.  Unfortunately, I'm seeing the following stack trace when attempting to deploy the license check plugin:

```
2017.10.19 20:36:09 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: The web service 'api/licenses' is defined multiple times
        at org.sonar.api.server.ws.WebService$Context.register(WebService.java:122)
        at org.sonar.api.server.ws.WebService$Context.access$300(WebService.java:102)
        at org.sonar.api.server.ws.WebService$NewController.done(WebService.java:160)
        at at.porscheinformatik.sonarqube.licensecheck.webservice.license.LicenseWs.define(LicenseWs.java:53)
        at org.sonar.server.ws.WebServiceEngine.<init>(WebServiceEngine.java:66)
```
The server configuration is attached.  I'm not really sure what might be going on or how to determine what is already using the particular endpoint.  Can you offer any insights?

[sonar_system_info.json.zip](https://github.com/porscheinformatik/sonarqube-licensecheck/files/1399922/sonar_system_info.json.zip)

**Comment by derkoe** [comment]
Currently the plugin only supports SonarQube 5.3 to 5.6.x (LTS). 

I have created an issue for the support of SonarQube 6.x #13 (PRs welcome)

**Comment by derkoe** [comment]
I have create a new release [2.0.0-beta-1](https://github.com/porscheinformatik/sonarqube-licensecheck/releases/tag/2.0.0-beta-1) that supports SonarQube > 6.5. Could you give it a try?

**Comment by csetera** [comment]
I will find some time to check this out. Thanks!

**Comment by csetera** [comment]
This appears to be working.  With that said, it seems like I'm missing a lot of licenses for things that the license should be able to be derived.  For instance, the component ant:ant:1.6.5 has no immediate license.  However, it has the parent org.apache:apache:4.  In that POM file, is the Apache license.

Is that expected behavior?  If not, is it possible to add that functionality?

**Comment by csetera** [comment]
Looking at the plugin source, I see that it is trying to find the parent pom and look at the license in that file.  However, that doesn't seem to be working.  I'm not entirely sure why it isn't working or how to even figure that out.  I'm more than willing to do some digging if you can offer some direction on where and how to look.

**Comment by derkoe** [comment]
That is expected behavior. The reason for this is that Maven has no defined format to define licences - one can write anything in the name tag of the license. To map the Maven free-text licenses to the [SPDX list](https://spdx.org/licenses/) you can define a Regex to license mapping in the configuration under "Maven Licenses" (for local installation http://localhost:9000/admin/extension/licensecheck/configuration?category=maven-licenses). Add an entry ".*Apache.*2.*" -> "Apache-2.0 / Apache License 2.0" which should do the trick. 

I have created a new issue (#15) to add default mappings.

**Comment by csetera** [comment]
I will give that a try.

**Comment by csetera** [comment]
I just gave this a try.  Despite not seeing any errors in the log, adding the new license mapping does not seem to "stick".

**Comment by derkoe** [comment]
What do you mean by that? 

Here you see how to configure the Maven Licenses:
![image](https://user-images.githubusercontent.com/123199/34510281-e5b1235a-f052-11e7-9a02-d4f4aca320ba.png)

**Comment by csetera** [comment]
I mean that I go to that page.  I press the "Add Maven License" button.  The dialog comes up.  I enter the information into the dialog.  I press the "Save" button.  And nothing happens.  Nothing is added to the list below.  There are no errors in the logs and the new mapping is not added.  

If you need me to create a new issue to track this, please let me know.

**Comment by derkoe** [comment]
@csetera please create an issue and add the output in the browser console (if any).

**Comment by csetera** [comment]
Well... that was strange.  When I tried to recreate this to collect the console errors, it worked as it should have.  I have no idea why it may not have worked before, but it seems to be correct now.  I had to change the regular expression you suggested a bit to get it to work, but it does work... so excellent work!  Thanks so much for your help.
