### ISSUE TITLE
enhancement: switch "Dependencies" table and "Licenses" table in UI and Export

### ISSUE THREAD

**Issue by Janpopan** [porscheinformatik/sonarqube-licensecheck#118]
so you see first if there is a forbidden license in your project.

And you should add a "unknown License" row in table "Licenses" if there is at least one in the project

**Comment by Janpopan** [comment]
50% are solved from 3.2.0/4.0.0 ; but I think I forgott the "unknown" row

**Comment by derkoe** [comment]
> And you should add a "unknown License" row in table "Licenses" if there is at least one in the project

I think this is not possible since the license table is in the settings which cannot be changed during the scan.
