### ISSUE TITLE
Cannot start sonarqube with plugin installed.

### ISSUE THREAD

**Issue by blackmob** [porscheinformatik/sonarqube-licensecheck#12]
I am currently building a sonarqube docker image and was intending to use your plugin.  The stack trace is below. I have attached the dockerfile.
[Dockerfile.txt](https://github.com/porscheinformatik/sonarqube-licensecheck/files/1399927/Dockerfile.txt)

sonarqube_1     | java.lang.IllegalStateException: The web service 'api/licenses' is defined multiple times
sonarqube_1     |       at org.sonar.api.server.ws.WebService$Context.register(WebService.java:122)
sonarqube_1     |       at org.sonar.api.server.ws.WebService$Context.access$300(WebService.java:102)
sonarqube_1     |       at org.sonar.api.server.ws.WebService$NewController.done(WebService.java:160)
sonarqube_1     |       at at.porscheinformatik.sonarqube.licensecheck.webservice.license.LicenseWs.define(LicenseWs.java:
53)
sonarqube_1     |       at org.sonar.server.ws.WebServiceEngine.<init>(WebServiceEngine.java:66)
sonarqube_1     |       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sonarqube_1     |       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sonarqube_1     |       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.jav
a:45)
sonarqube_1     |       at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
sonarqube_1     |       at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
sonarqube_1     |       at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
sonarqube_1     |       at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractI
njector.java:270)
sonarqube_1     |       at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:3
64)
sonarqube_1     |       at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(Abst
ractInjectionFactory.java:56)
sonarqube_1     |       at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
sonarqube_1     |       at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
sonarqube_1     |       at org.picocontainer.DefaultPicoContainer.instantiateComponentAsIsStartable(DefaultPicoContainer.j
ava:1034)
sonarqube_1     |       at org.picocontainer.DefaultPicoContainer.addAdapterIfStartable(DefaultPicoContainer.java:1026)
sonarqube_1     |       at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1003)
sonarqube_1     |       at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
sonarqube_1     |       at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:143)
sonarqube_1     |       at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:88)
sonarqube_1     |       at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:533)
sonarqube_1     |       at org.sonar.server.platform.Platform.start(Platform.java:231)
sonarqube_1     |       at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:205)
sonarqube_1     |       at org.sonar.server.platform.Platform.access$500(Platform.java:46)
sonarqube_1     |       at org.sonar.server.platform.Platform$1.lambda$doRun$0(Platform.java:119)
sonarqube_1     |       at org.sonar.server.platform.Platform$AutoStarterRunnable.runIfNotAborted(Platform.java:391)
sonarqube_1     |       at org.sonar.server.platform.Platform$1.doRun(Platform.java:119)
sonarqube_1     |       at org.sonar.server.platform.Platform$AutoStarterRunnable.run(Platform.java:375)
sonarqube_1     |       at java.lang.Thread.run(Thread.java:748)

**Comment by derkoe** [comment]
Currently the plugin only supports SonarQube 5.3 to 5.6.x (LTS). 

I have created an issue for the support of SonarQube 6.x #13 (PRs welcome)

**Comment by derkoe** [comment]
I have create a new release [2.0.0-beta-1](https://github.com/porscheinformatik/sonarqube-licensecheck/releases/tag/2.0.0-beta-1) that supports SonarQube > 6.5. Could you give it a try?
