### ISSUE TITLE
projectLicense in subpackage should be projectlicense

### ISSUE THREAD

**Issue by Janpopan** [porscheinformatik/sonarqube-licensecheck#156]
at.porscheinformatik.sonarqube.licensecheck.projectLicense
->
at.porscheinformatik.sonarqube.licensecheck.projectlicense

**Comment by derhecht** [comment]
could you may provide the current situation and the wanted change/expected situation?

**Comment by Janpopan** [comment]
It is just a Code smell with the uppercase
