### ISSUE TITLE
Gradle Support added

### ISSUE THREAD

**Issue by xellsys** [porscheinformatik/sonarqube-licensecheck#17]
Hi,

Great plugin, thanks for open sourcing it!
I have recently forked it and added basic gradle support. Are you interested in merging that feature into your repository?
You can find the sources here: https://github.com/xellsys/sonarqube-licensecheck
Some open points on my end:
- In the process of gathering the gradle dependencies I'm currently executing gradle (or gradlew if available) via java process execution. I think taking leverage of the gradle tooling api would be the cleaner choice. The best way would be to access the classes in the context the plugin is being executed in - however I'm uncertain if that is even possible. I would need to get a reference to the current project instance.
- For the gradle process I'm also adding the -I flag for additional init script support (if the sonarqube task was called with additional init scripts). I believe reusing all or selected flags would be beneficiary (eg: --build-file)
- To support the package -> license and regex -> license association features I had to access MavenLicenseService and MavenDependencyService. This is functionally redundant to the code in MavenDependencyScanner. Ideally this should be moved to a shared package.
- I have added a ScannerResolver class which dynamically recognises whether it's a gradle or maven project. I'm not 100% certain this is the best way to go.
- I have added some tests, but was unable to perform extensive manual / regression tests.
- A general remark: there are other plugins out there gathering more extensive license information by parsing license files and such. This would also be an improvement I'm currently looking into - although rather independent from the gradle support.

best regards,
Benny

**Comment by derkoe** [comment]
Sorry for the late response - yes we'd be interested in adding Gradle support.

I think forking a process is ok. Another option would be to read the results from a file.

Please send a PR.

**Comment by derkoe** [comment]
Gradle support added via #177
