### ISSUE TITLE
No dependencies for NPM

### ISSUE THREAD

**Issue by ksastan** [porscheinformatik/sonarqube-licensecheck#175]
Hi!
I've installed sonarqube-licensecheck plugin and activate rules for it.
In sonarqube execution log I see flowing messages:
` ...
12:00:52.828 DEBUG: Sensors : JavaXmlSensor -> License Check -> SonarTS -> JavaScript analysis -> TypeScript analysis
 12:00:52.828 INFO: Sensor JavaXmlSensor [java]
 12:00:52.833 INFO: Sensor JavaXmlSensor [java] (done) | time=5ms
 12:00:52.834 INFO: Sensor License Check [licensecheck]
 12:00:52.875 DEBUG: Saving depenencies for module [key=test-project]: []
 12:00:52.876 DEBUG: Saving licenses for module [key=test-project]: []
 12:00:52.877 INFO: Sensor License Check [licensecheck] (done) | time=43ms
 12:00:52.878 INFO: Sensor SonarTS [typescript]
...`

Not empty file package.json existed in the root of project but there are no dependencies.
There are no errors in sonar logs.
I can't understand what I did wrong or it  is the issue in plugin.

**Comment by derkoe** [comment]
Did you activate the rules ("License is not allowed", "Dependency has unknown license") in your SonarQube quality profiles?

**Comment by ksastan** [comment]
Yep, this rules were activated
I'll close the issue because haven't had access to sonar installation anymore
