### ISSUE TITLE
Add support for SonarQube 8.x

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/sonarqube-licensecheck#176]
SonarQube 8.x changed some APIs so that this plugin is no longer compatible. Update and use the new 8.x API.

**Comment by GrannyOlli** [comment]
Hi, i want to kindly ask if there is progress on this issue. Thank you!

**Comment by derkoe** [comment]
First beta release https://github.com/porscheinformatik/sonarqube-licensecheck/releases/tag/v4.0.0-beta-1
