### ISSUE TITLE
Error 400 when trying to add new license with "Allowed" not checked

### ISSUE THREAD

**Issue by tediroca** [porscheinformatik/sonarqube-licensecheck#209]
Sonar: 8.5.0.37579
sonarqube-licensecheck: 4.0.0

1. Add a new license - works fine.
2. Add a second license without leaving the screen - it fails.
![image](https://user-images.githubusercontent.com/1898632/98933154-8c4c0a80-24e0-11eb-83ce-5ae0d688a1a0.png)

![image](https://user-images.githubusercontent.com/1898632/98933251-af76ba00-24e0-11eb-9883-6531a18963bd.png)

As a workaround you can enable and disable the status checkbox, and it would save it correctly.

**Comment by derkoe** [comment]
Ah the problem occurs when you add a new license with status "Allowed" not checked.

**Comment by tediroca** [comment]
Yeah, exactly! But if I enable and disabled it again, then it works fine
too.

Regards / Saludos / Salutacions,

Tedi Roca
https://tedi.es

**Comment by derkoe** [comment]
Fixed in [4.0.2](https://github.com/porscheinformatik/sonarqube-licensecheck/releases/tag/v4.0.2)
