### ISSUE TITLE
NPM doesn't support transitive dependendies

### ISSUE THREAD

**Issue by meddox** [porscheinformatik/sonarqube-licensecheck#21]
Would be great that plugin can check also transitive dependencies for npm projects.

**Comment by derkoe** [comment]
I'm not sure if this would be a good idea in general since many npm modules declare deps but don't need them when running. Maybe with a config switch?

Anyway PRs welcome :)

**Comment by oliverlockwood** [comment]
@derkoe PR raised - please do give it a review when you have the chance!  Thanks.

**Comment by HSSE-Dev** [comment]
Hello just to make sure, the scanning of transitive dependencies is not yet available in version 3.1.1, because the description is already available in the ReadMe?
The property would then be set to "sonar.licensecheck.npm.resolvetransitive=true"?
