### ISSUE TITLE
Npm check does nothing - No output

### ISSUE THREAD

**Issue by axi92** [porscheinformatik/sonarqube-licensecheck#213]
I am checking an electron app with several dependencies but got just js/html/... checked and not the dependency licenses.
![grafik](https://user-images.githubusercontent.com/1394837/105034063-44ee7700-5a59-11eb-9174-8bb649ef366c.png)

I added those conditions and it is the default gate.
![grafik](https://user-images.githubusercontent.com/1394837/105034261-82530480-5a59-11eb-8f13-372c31c4bc31.png)

Have I missed something?

**Comment by Janpopan** [comment]
The scanner works only if you have At least one java file in your project.

**Comment by derkoe** [comment]
And you have to enable the rule in your Java quality profile.

**Comment by derkoe** [comment]
This issue will be addressed by splitting Java and JavaScript. Duplicate of #42
