### ISSUE TITLE
Enable the use of package-lock.json instead of package.json

### ISSUE THREAD

**Issue by thdoucet** [porscheinformatik/sonarqube-licensecheck#214]

**Comment by derkoe** [comment]
The current implementation takes the currently installed packages under node_modules. This works with all package mangers (yarn, npm, pnpm). 

I'm also not sure how using package-lock.json would help. There are no license infos in this file.

**Comment by derkoe** [comment]
@thdoucet ? Any more input?

**Comment by thdoucet** [comment]
Sorry, my understanding was the implementation use the package.json to retrieve the dependencies. Using the package-lock.json may add some informations about dependencies.
As the node_modules folder is used, my request has no sence.
My apologies, I close this issue.
