### ISSUE TITLE
How to use the plugin with maven

### ISSUE THREAD

**Issue by ibarrancos** [porscheinformatik/sonarqube-licensecheck#216]
I'm trying to use the plugin with sonarqube community 8.4.2 (build 36762). 
I installed the plugin on the server, and the options shows as written in README.md.

![Sonar01](https://user-images.githubusercontent.com/13077582/105673607-8f9f4180-5ee6-11eb-8247-76a1e65e4f78.png)

![Sonar02](https://user-images.githubusercontent.com/13077582/105673615-9332c880-5ee6-11eb-878d-a4521231d574.png)

Then run maven,

```bash
mvn clean -DfailOnError=false \
          -Dformats=ALL \
          org.jacoco:jacoco-maven-plugin:prepare-agent \
          verify \
          org.jacoco:jacoco-maven-plugin:report \
          org.owasp:dependency-check-maven:6.0.5:aggregate \
          org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar \
          -Dsonar.dependencyCheck.summarize=true \
          -Dsonar.host.url=https://sonarqube-pru.carm.es \
          -Dsonar.gitlab.project_id=glpi \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
          -Dsonar.coverage.exclusions=**/*.html,**/*.css,**/*.png,**/*.jpg,**/*.JPG \
          -Dsonar.junit.reportsPath=target/dependency-check-junit.xml \
          -Dsonar.login=$AUTH_USER_LOGIN \
          -Dsonar.password=$AUTH_USER_PASS  \
          -Dsonar.verbose=true \
          -Dsonar.sourceEncoding=UTF-8
```

It runs without errors, but does not write any reports with the licenses: ```find -iname "*licen*" ``` ...it's empty. In the server console, the section also appears empty

![Sonar03](https://user-images.githubusercontent.com/13077582/105673581-8615d980-5ee6-11eb-84aa-d9576f1ad4e7.png)

I am using Java 11 and maven 3.6.1 on Linux. Also, i have tried sonar-maven-plugin version 3.7.0.1746, and run ```install``` instead of ```verify```, but with the same result.

How can I force the plugin to run locally and post the report to the server?

**Comment by derkoe** [comment]
Did you enable the two rules in the quality profile for the project (https://github.com/porscheinformatik/sonarqube-licensecheck#installation)?

**Comment by ibarrancos** [comment]
@derkoe  thanks for your reply :)

**That was the problem, Great!...  Thank you so much.**


1) I create a new Quality Profile that extends from SonarWay, and configure as default

![Pantallazo-01](https://user-images.githubusercontent.com/13077582/105844439-893dc200-5fd9-11eb-9369-dc0b5acdcf7d.png)

2) The differences between two Quality Profiles are the license-check rules 

![Pantallazo-02](https://user-images.githubusercontent.com/13077582/105844459-8f33a300-5fd9-11eb-8a65-8f560cfdb824.png)

3) Then, I run maven and now it does publish the report :)

![Pantallazo-03](https://user-images.githubusercontent.com/13077582/105844474-9490ed80-5fd9-11eb-901e-7b5f11fc2655.png)
