### ISSUE TITLE
License check plugin: The library showing incorrect license

### ISSUE THREAD

**Issue by mansing2** [porscheinformatik/sonarqube-licensecheck#220]
We have configured the new Sonar with v8.5.1 and the old one is with v6.7.4.

We have recently activated https://github.com/porscheinformatik/sonarqube-licensechec plugin and activated licenses statuses as per our old instance.

The issue is: The dependency license for one of the libraries is showing incorrect, and not as per our old sonar, the configuration is the same as the old sonar.
Screenshot 1 (old sonar)  - 
![image](https://user-images.githubusercontent.com/25703880/109161293-e2e20980-779c-11eb-8863-194efc99ff81.png)

Screenshot 2 (new sonar) - 
![image](https://user-images.githubusercontent.com/25703880/109161234-d2ca2a00-779c-11eb-8ef5-83bc44f35e54.png)
 

Steps to reach this place: 1. Project Settings-> More->License Check

Does anybody have any idea how these settings can be changed to align a library with a required license?

**Comment by derkoe** [comment]
This is package has dual licensing (see https://search.maven.org/artifact/org.codehaus.jackson/jackson-jaxrs/1.9.5/jar).

So this seems like an Set ordering issue (this can happen when changing the JVM or host or anything).

The easiest way to workaround this is to define the Maven dependency to license mapping in the settings. 

I have created a new feature request #221 and will close this issue.

**Comment by mansing2** [comment]
@derkoe  - That helps, I have added the maven dependency to map the particular library/package to the license.
