### ISSUE TITLE
Actions not displaying on 7.1

### ISSUE THREAD

**Issue by aguerrieri** [porscheinformatik/sonarqube-licensecheck#23]
Action icons do not display in SonarQube OSS 7.1.0.11001

![screenshot 2018-10-03 15 03 37](https://user-images.githubusercontent.com/4050808/46432963-92763700-c71d-11e8-9bbb-f6658bb1ab82.png)

**Comment by aguerrieri** [comment]
I was able to "edit" a license by manipulating the DOM (that's why the first row shows "true")

**Comment by derkoe** [comment]
We are currently only supporting the LTS version 6.7.x - maybe future versions will support 7.x

**Comment by derkoe** [comment]
Created a new pre-release [3.0.0-beta-1](https://github.com/porscheinformatik/sonarqube-licensecheck/tree/v3.0.0-beta-1) for that.
