### ISSUE TITLE
Missing pre-built jar-file for v4.0.2

### ISSUE THREAD

**Issue by stevehipwell** [porscheinformatik/sonarqube-licensecheck#231]
The _pre-built jar-file_ for `v4.0.2`; referred to in the installation documentation is missing.

**Comment by derkoe** [comment]
Release is fixed now https://github.com/porscheinformatik/sonarqube-licensecheck/releases/tag/v4.0.2

**Comment by stevehipwell** [comment]
Thanks for the quick response and fix @derkoe.
