### ISSUE TITLE
Usage with NPM projects

### ISSUE THREAD

**Issue by vinodkumar4b9** [porscheinformatik/sonarqube-licensecheck#239]
Hi All,

Actually recently we have setup a Sonarqube license check plugin and it is showing as expected , Ryt now we are using Sonarqube enterprise version . May I know how I need to use this plugin for NPM projects and what details it will give for me when i ran the scan and use this plugin ??

**Comment by derkoe** [comment]
Currently, you'll have to enable the rules in the Java Quality Profile and add at least one empty Java file. See #213

I'm currently working on a solution for this.

**Comment by vinodkumar4b9** [comment]
Hi @derkoe ,

Actually we dont have any Java files as of now and only thing we are scanning is Nodejs/react js projects And Any idea how to use this plugin without adding Java files into the current repo

**Comment by derkoe** [comment]
@vinodkumar4b9 as I said the current workaround is to add a simple Java file to your project (any will do).
