### ISSUE TITLE
Actions not displaying in SonarQube version 7.3

### ISSUE THREAD

**Issue by nansaab** [porscheinformatik/sonarqube-licensecheck#25]
![image](https://user-images.githubusercontent.com/44668491/48054396-74cd3f00-e1ad-11e8-97c2-9b9c28ff14da.png)

**Comment by nansaab** [comment]
This looks like a very interesting plugin to analyse source code for what licenses it relies on as external dependencies. I've not currently gotten this to work yet.

As a follow up question will this plugin be able to scan different files (.h, .cpp, .cs .java etc) for valid or invalid licenses used?

Best regards Niklas Andersson

**Comment by aaverkova** [comment]
Have you tried the new pre-release for 7.x? https://github.com/porscheinformatik/sonarqube-licensecheck/releases/tag/v3.0.0-beta-1

**Comment by nansaab** [comment]
Hi, 
Hi, 

First I was mistakingly using version 2.0.0, since I was too fast downliading the plugin, there were no release comments on that version. I later replaced the 2.0.0 plugin with version 3.0.0-beta-1 and restarted the server and the problem in the screen shot above appeared.

When I logged in to the server this morning the error is somehow gone. I can now see the Actions and Edit parts of the UI under Administration->Configuration->License Check.

Sorry for this, I think you can close this issue.

Did you see my comment about opening up this plugin to scan for more type of files. I Think you will broaded your user base if it would be possible to scan more type of files.

From my own perspective it would be great if it would be possible to scan:

Source code files:
.cpp, .c, .h. .hpp, cs, .js

Nuget packages:
.nuget, .nuspec

Best Regards
Niklas Andersson
First I was mistakingly using version 2.0.0, since I was too fast downliading the plugin, there were no release comments on that version. I later replaced the 2.0.0 plugin with version 3.0.0-beta-1 and restarted the server and the problem in the screen shot above appeared.

When I logged in to the server this morning the error is somehow gone. I can now see the Actions and Edit parts of the UI under Administration->Configuration->License Check.

Sorry for this, I think you can close this issue.

Did you see my comment about opening up this plugin to scan for more type of files. I Think you will broaded your user base if it would be possible to scan more type of files.

From my own perspective it would be great if it would be possible to scan:

Source code files:
.cpp, .c, .h. .hpp, cs, .js

**Comment by nansaab** [comment]
I'm closing this issue and opening a new feature request regarding the other files to scan.
