### ISSUE TITLE
Tests / Code Coverage

### ISSUE THREAD

**Issue by Janpopan** [porscheinformatik/sonarqube-licensecheck#253]
I try to improve test an code coverage. I use diffblue, the branch is not ready. 
I have questions:
1) is this helpfull?
2) how can I exchange me with others here?
2.1) create a unfinished pull request and discuss there?
2.2) is there a chat ore something like this?

You can find the source in my fork in branch improve_test.

Cheers 
Jan

**Comment by derkoe** [comment]
1. I'm not sure - it depends if the tests do anything useful or just create coverage. I've looked at some of the code in https://github.com/Janpopan/sonarqube-licensecheck/tree/improve_test and it looks like most of the tests make no sense:
    ```
    @Test
    public void testGetName() {
        assertEquals("Name", (new Dependency("Name", "1.0.2", "License")).getName());
    }
    ```
    I think it would be helpful to add some tests - but I guess that have to be hand-coded. PRs welcome!

2. I have enabled [GitHub Discussions](https://github.com/porscheinformatik/sonarqube-licensecheck/discussions) some weeks ago - this is a good place to discuss stuff.
