### ISSUE TITLE
Details regarding the Plugin

### ISSUE THREAD

**Issue by vinodkumar4b9** [porscheinformatik/sonarqube-licensecheck#258]
Hi @derkoe ,

Regarding this Plugin Can you please provide us some details here , So Basically once you install the plugin and then based on the project we work we need to add the licenses .

So Here Based on the licenses we add it will show you the details whether this has been allowed or not ryt ? and if you don't have any details regarding that It will show the status as Unknown . Is my understanding correct ? or Is there any way that this can say that the version we are using is not the latest or updated one some thing like that

Can you please give us a brief how this plugin exactly works so that I will be useful for me to proceed further

**Comment by derkoe** [comment]
Moved to discussions #259
