### ISSUE TITLE
Dockercontainer available?

### ISSUE THREAD

**Issue by SpatialJ** [porscheinformatik/sonarqube-licensecheck#277]
Is there a (maybe even official) docker container available for this plugin?

**Comment by derkoe** [comment]
I'm not sure about this question. sonarqube-licensecheck is a plugin for [SonarQube](https://www.sonarqube.org/). So you need to add the plugin to an installed instance of SonarQube.

There is a [Docker image for SonarQube](https://github.com/SonarSource/docker-sonarqube) which you can use.

**Comment by SpatialJ** [comment]
The question intended wether somebody already created a container image (e.g. based on the official sonarqube image) that has this plugin already baked into it. Im currently  running sonarqube using the offcial image and it would be convenient to use an existing image including the plugin :-)

**Comment by derkoe** [comment]
I do not think this is a good idea since most people are using multiple plugins. All the other plugins also do not provide Docker images like that.
