### ISSUE TITLE
project mapping limitation - 100 projects

### ISSUE THREAD

**Issue by Janpopan** [porscheinformatik/sonarqube-licensecheck#291]
In version 4.0.2 and 5.0.0 you can only map licenses in first 100 sonar projects.
![image](https://user-images.githubusercontent.com/1523002/144236643-498eb707-2a8d-4a8c-a04b-e5cadc9f225a.png)

**Comment by Janpopan** [comment]
@derkoe I think I found the bug in sonar-api.js
``
 .getJSON('/api/components/search?qualifiers=TRK&pageSize=500') // TODO > 500 projects?

->

 .getJSON('/api/components/search?qualifiers=TRK&ps=500') // TODO > 500 projects?
``

so the bug is also up to 5.0.0. 

I can open a PR.

**Comment by derkoe** [comment]
@Janpopan PR would be great - guess you'll have to page

**Comment by Janpopan** [comment]
https://github.com/porscheinformatik/sonarqube-licensecheck/pull/296

**Comment by derkoe** [comment]
Fixed by #296
