### ISSUE TITLE
NPM licenses for project empty

### ISSUE THREAD

**Issue by sebbes** [porscheinformatik/sonarqube-licensecheck#309]
Hi, I installed the plugin (in the latest version) on Sonarqube LTS (8.9.7) and it works well with a Java/Maven project. But for an Angular project the license check overview in the project itself is empty. Can anyone shed light into making npm executions work with this plugin?

**Comment by derkoe** [comment]
If you have the NPM project in the Maven structure you can use the SonarQube Maven plugin and it just works. When you have a separate instance you'll have to use the https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/

For a working example you can look at https://github.com/porscheinformatik/angular-spring-heroes - the analysis is done via GitLab CI here: https://github.com/porscheinformatik/angular-spring-heroes/blob/8c0bf4921e852e885b7d8a27e108e2b5d0617a1e/.gitlab-ci.yml#L34-42

**Comment by sebbes** [comment]
Hi, thanks for your reply. Unfortunately also with the repo mentioned the licences overview for [angular-spring-heroes](https://github.com/porscheinformatik/angular-spring-heroes) is empty in my sonar. I executed the steps from the Gitlab CI job `build-sonarqube-qa`, without success.

![sonar-licences-empty](https://user-images.githubusercontent.com/1336217/155539837-7c4f5b1d-5e73-4d02-a39e-ac79b0135492.PNG)

For a Java/Maven project it produces this report:

![sonar-licences-valid](https://user-images.githubusercontent.com/1336217/155543537-a84c57f4-d0c3-49fe-a5c2-06c403a9bcea.PNG)

Plugin-version: 5.0.0, Sonarqube-version: 8.9.7 (LTS)

**Comment by sebbes** [comment]
Hi, thanks or your reply. I tested the repository https://github.com/porscheinformatik/angular-spring-heroes. It only shows the licenses from the backend, none from the frontend. How to show licenses from the an npm repository? In your README you state: "NPM works if your project/module has a package.json on its root level (running with Maven, Gradle or SonarScanner)."

**Comment by derkoe** [comment]
Sorry the config in this project was wrong - package.json was not analyzed by SonarQube: here is the fix https://github.com/porscheinformatik/angular-spring-heroes/commit/e36f4b90bdd3248b35f33e686d5996575a16ee36

**Comment by sebbes** [comment]
Cool, thanks. Now I can see the licenses for the frontend as well. Will try now myself to get it working in a standalone project. Thanks a lot for your support!!!
