### ISSUE TITLE
No way to scan submodules

### ISSUE THREAD

**Issue by csetera** [porscheinformatik/sonarqube-licensecheck#34]
As part of #22 , the support for submodules was removed.  Unfortunately, that was a feature we depended on for the license check.  After updating to 2.0.0 (non-beta) our builds no longer produce any output for this plugin.  Would it be possible to make this a configurable value so that we can re-enable submodule traversal?

**Comment by derkoe** [comment]
How do you analyze your project? When you do an "mvn clean verify sonar:sonar" as stated in [Analyzing with SonarQube Scanner for Maven](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner+for+Maven) all your Maven modules will be analyzed by this plugin. 

#22 fixed the issue that sub-modules were analyzed even when "sonar.skip" was set for this module.

**Comment by csetera** [comment]
Hello,

We currently have installed sonarqube-licensecheck-plugin-2.0.0-beta-1.jar (manually) into our instance.  We have it configured to run for our EAR project, which consists of 2 WARs made up of multiple JAR files.  With that version of the plugin, we see all of the license information gathered recursively down to the JARs.  If we switch to a newer version, we see no license information.

**Comment by derkoe** [comment]
We are scanning over 200 projects with modules and all work - can you share your POMs?

**Comment by csetera** [comment]
Would you need the full set of POMs or just a small subset that shows our overall structure?

**Comment by derkoe** [comment]
Just tried a plain new install of SonarQube 6.7.6 + the sonarqube-licensecheck plugin in version 2.0.0 with the following project: https://github.com/porscheinformatik/angular-spring-heroes 

Result: all dependencies show up (npm + Maven).

Please check your configuration with this project.

**Comment by derkoe** [comment]
@csetera any news on this - otherwise I will close this issue.

**Comment by csetera** [comment]
Apologies... I've just been swamped and have not had a chance to dig into this any deeper.  If you need to close this, you can go ahead.  If I can get more details in the future, I can open a new ticket at that point.
