### ISSUE TITLE
use an OpenApi tool for API documentation

### ISSUE THREAD

**Issue by Janpopan** [porscheinformatik/sonarqube-licensecheck#340]
I think it could be use full to document the API by an tool.
Or just JavaDoc?

**Comment by Janpopan** [comment]
Ok there is a build in solution
http://localhost:9000/api/settings/list_definitions

**Comment by derkoe** [comment]
For which API? This plugin does not provide any REST API. It just uses the [SonarQube API](https://docs.sonarqube.org/latest/extend/web-api/).
