### ISSUE TITLE
POM inside submodule

### ISSUE THREAD

**Issue by ckocyigit** [porscheinformatik/sonarqube-licensecheck#344]
Hello all,

the README says that this is only working for maven projects where the pom.xml is in the root directory.
Is this still valid? 

We have a lot of projects where the main pom is within a "parent module".

Thank you!

**Comment by derkoe** [comment]
The Sonar Maven Plugin usually just works when you have the pom.xml in the current folder. I guess the parent can be in any folder (or even in a Maven repository).

Do you have any issues?
