### ISSUE TITLE
Scala (Sbt) License Support 

### ISSUE THREAD

**Issue by thalesdev** [porscheinformatik/sonarqube-licensecheck#348]
Is there any way to use sonarqube-licensecheck with Scala?

**Comment by Janpopan** [comment]
Hello @thalesdev, 

at hte moment scala is not supported or still missing ;-)

You can try an workaround:

Create at least on file with a supported language and enable the licensechekc rules for this language for your project.
Then it could work.

And can you explain a little bit more about your project setup or habe you a link to the repo?

Cheers
Jan

**Comment by thalesdev** [comment]
Hey @Janpopan,
Well I got to take a look at the pr code you mentioned, but I don't understand much about java.
About the repository I was trying with a configuration similar to this repository here: https://github.com/thalesdev/scala-sonarqube-license-check.
I've tried generating poms, like `sbt makePom` and `sbt makePomMove` and still no success. I also tried from the generated `pom` to create a `build.gradle` and try like this, but I couldn't either.

**Comment by Janpopan** [comment]
@thalesdev sorry, it is more complex than I thought. My patch add the support for the scala language. But no support for sbt.
To support sbt, there is more work needed.

[see here](https://github.com/porscheinformatik/sonarqube-licensecheck#supported-project-types)

I have no Idea about scala or sbt. Can you tell me, which sbt command is used to list the license infos in the project?

I have found a sbt plugin for this usecase.
