### ISSUE TITLE
Kotlin seems to not be supported on 5.1.0

### ISSUE THREAD

**Issue by ittocean** [porscheinformatik/sonarqube-licensecheck#350]
Hi,

Plugin version 5.1.0
SonarQube 9.5

I'm running analysis on a kotlin-only project, and do not get the license analysis results.
Using the maven sonar command "mvn sonar:sonar ..." - the only logs I get from licensecheck are -

11:42:38.811 [INFO] Sensor License Check [licensecheck]
11:42:38.816 [INFO] No license-details.json file found in /builds/my-project/build/reports/dependency-license/license-details.json - skipping Gradle dependency scan
11:42:38.828 [INFO] Sensor License Check [licensecheck] (done) | time=16ms

The same sonar command executed on a different projects (npm, java - I have several) does yield results.

I see from this ticket that Kotlin support was fixed on 5.0.1
https://github.com/porscheinformatik/sonarqube-licensecheck/issues/310

Perhaps there is a regression?

Thanks.

**Comment by Janpopan** [comment]
Did this work for you before?
Did you setup a kotlin rule set with (additional) the two licensencheck rules and did you use them for your project?

**Comment by Janpopan** [comment]
@derkoe in my opinion there is somthing missing in ValidateLicenses, what do you think?

**Comment by Janpopan** [comment]
@ittocean can you provide your project setup or a public mockup? You use Kotlin with maven and node?

**Comment by ittocean** [comment]
@Janpopan , I apologize for the late response.

The project (or projects) I'm having this trouble with are kotlin with maven, only. They are not public.
Our SQ is also private and on-premise so I can't share a public mockup project, if I understand you right.
I do have other projects, java with maven, node with .. well, npm.. but there I'm using sonar-scanner directly. They work fine, the license report is generated and present on SQ.
As for the kotlin projects, their scanning is executed by maven command -

mvn -f pom.xml -s settings.xml sonar:sonar
      -Dsonar.host.url=${SONAR_HOST_URL}
      -Dsonar.login=${SONAR_AUTH_TOKEN}
      -Dsonar.projectVersion=${BUILD_DISPLAY_NAME}
      -Dsonar.qualitygate.wait=${AWAIT_QUALITY_GATE}
      -Dsonar.qualitygate.timeout=300
      -Dsonar.branch.name=${CI_COMMIT_BRANCH}

Note that I do not have sonar scanner maven plugin setup in my pom.xml
Maybe version-wise, by using "sonar:sonar", I'm stuck on an old scanner version? idk. :)
On the other hand, I do use the same command (same CI template) for the java+maven projects.

The image the command is executed from is an untainted - maven:3-openjdk-11

My quality profile is an extension of the default Sonar Way, and the only change on it is adding the two licensecheck rules.

I suspected maybe it was related to not having master as main branch (on SQ), but that is not it, most projects I have this issue on do have master as their main branch.
