### ISSUE TITLE
Sonarqube 9.9 LTS compatibility

### ISSUE THREAD

**Issue by rdsubhas** [porscheinformatik/sonarqube-licensecheck#362]
Opening a thread for any ongoing discussions/questions about Sonarqube 9.9 LTS compatibility.

According to the README: https://github.com/porscheinformatik/sonarqube-licensecheck#compatibility

> This plugin is compatible:
> 5.x version with 8.9 LTS and <= 9.7.x

Technically there don't seem to be any big breaking changes between 9.7 and 9.9, so maybe it could work out of the box. We will be testing soon, but just opening an issue to track any issues and update the doc as necessary.

**Comment by sschulz92** [comment]
Is there any schedule to check the compatibility with SonarQube 9.9? :)
