### ISSUE TITLE
Multiple node_modules

### ISSUE THREAD

**Issue by mutagenspree** [porscheinformatik/sonarqube-licensecheck#369]
Hi! We are using pnpm as a package manager. After installing dependencies,  pnpm creates "node_modules" directories in modules folders and simlinks from `./node_modules/.pnpm/node_modules` to these folders. But pnpm creates simliks only for dependencies that are used in this module. It looks like sonar looking for modules package.json files in "node_modules" in the root of the project instead of "node_modules" in modules dirs. Because I see module @testing-library/jest-dom in `$PROJECT_DIR/modules/module_name/node_modules/@testing-library/jest-dom` but sonar skip this dependency - WARN: No package.json file found for package @testing-library/jest-dom in node_modules - skipping dependency
![Screenshot from 2023-03-17 17-02-30](https://user-images.githubusercontent.com/54075280/225957908-a84e589e-9303-4543-b45a-805ca836b6ef.png)

**Comment by derkoe** [comment]
Just tried this with pnpm and it works without any issue. 

@mutagenspree are you sure you have run `pnpm install` before the analysis?
