### ISSUE TITLE
Sonarqube Version 10.0 Compatibility

### ISSUE THREAD

**Issue by adamberent** [porscheinformatik/sonarqube-licensecheck#373]
When I install the plugin and click on More License Check, I get a blank screen.

<img width="1481" alt="Screenshot 2023-05-03 at 4 36 49 PM" src="https://user-images.githubusercontent.com/130793734/236065782-548aa0e8-7a44-4169-8ee0-3209556f6135.png">

**Comment by sjrsquared99** [comment]
I'm also interested in any feedback about this - and when it might be available

**Comment by fvclaus** [comment]
We have an internal auditing process that depends on this plugin. Because we can't wait much longer, I provided a MR for that fixes this problem.

**Comment by yevhenluhovtsov** [comment]
@fvclaus thanks for the fix. could you please clarify, does this fix works with SonarQube v10?

**Comment by fvclaus** [comment]
@seongilp Thanks for the feedback.

**Comment by sjrsquared99** [comment]
Hi

I took just the changes for dashboard.vue as I had already changed it to use the 10.1 SQ interface, and it works

THanks !

Simon Rowe
________________________________

**Comment by sjrsquared99** [comment]
Hi

But I am getting CSP errors when I move to 10.1. It is refusing to load the results dashboard and the Admin/config/licensecheck page 🙁

Kind REgards
Simon Rowe
________________________________

**Comment by fvclaus** [comment]
@sjrsquared99 I tested the admin page and didn't notice any problems:

![image](https://github.com/porscheinformatik/sonarqube-licensecheck/assets/2384738/3ae19552-511d-4aed-ac24-089aa29a0f2e)

To be honest: I don't understand why it works. I also don't understand how the settings page code is packaged and shipped to the frontend. The CSP restrictions should apply on the administration page as well.

Can you tell me which exact version of SonarQube you are using (including the build). I can fix that issue, if I am able to reproduce it.

**Comment by fvclaus** [comment]
Thanks. That doesn't work for me as well. I will provide a fix as soon as possible.

**Comment by sjrsquared99** [comment]
I'm already looking - if I get it working I'll send it to you

Kind REgards
Simon
________________________________

**Comment by fvclaus** [comment]
@sjrsquared99 I fixed the administration page:

![image](https://github.com/porscheinformatik/sonarqube-licensecheck/assets/2384738/24abf549-b093-48a9-b12f-7b199f5399b0)


You might need to reload with Ctrl+Shift+R to bypass the cached version of the old frontend.

Here is the new version with the fixed administration page: [sonarqube-licensecheck-plugin-6.0.0-alpha2.zip](https://github.com/porscheinformatik/sonarqube-licensecheck/files/11971707/sonarqube-licensecheck-plugin-6.0.0-alpha2.zip)

**Comment by muellerst-hg** [comment]
Please ping this issue when stable 6.x.x version was released. Unfortunately I cannot subscribe to github releases, but only to issues

**Comment by Breee** [comment]
any news for a stable + official release?
