### ISSUE TITLE
Will this plugin supports SonarQube 9.9 version

### ISSUE THREAD

**Issue by AsarudeenGithub** [porscheinformatik/sonarqube-licensecheck#377]
Hello Team,

we are using license check plugin with SonarQube 8.9 version, and we do not see compatible plugin for 9.9 version of sonarqube. can you please confirm whether the plugin supports SonarQube 9.9 LTS version & has it been tested?

if not do you have plan to release compatible version of this plugin for sonarqube 9.9 LTS version?

**Comment by derkoe** [comment]
The plugin is compatible with all 9.x versions - changed that in the readme: https://github.com/porscheinformatik/sonarqube-licensecheck/commit/33ba488bf96f1244c85f694b335865e8a5f15b58
