### ISSUE TITLE
naming conventions

### ISSUE THREAD

**Issue by rjacks24** [porscheinformatik/sonarqube-licensecheck#381]
Would it be possible or at least discussion worthy to name the files released the same as their actual release versions? 
i.e. v5.1.1 should be called sonarqube-licensecheck-plugin-**v**5.1.1.jar and not sonarqube-licensecheck-plugin-5.1.1.jar,

Or go with 5.1.1/sonarqube-licensecheck-plugin-5.1.1.jar is fine and dandy too.

**Comment by derkoe** [comment]
SonarQube plugins typically do not have a 'v' in the jar file name (still they all use 'v' in the tag), see [sonar-ansible ](https://github.com/sbaudoin/sonar-ansible/releases) or https://github.com/spotbugs/sonar-findbugs/releases
