### ISSUE TITLE
Number of Forbidden Licenses always eq to Number of Licenses with latest 9.9 LTS

### ISSUE THREAD

**Issue by jenspopp** [porscheinformatik/sonarqube-licensecheck#406]
With the latest 9.9 LTS I get always the number of forbidden licenses to equal the total number of licenses found. The license report says that all licenses are allowed but the quality gate fails:

![image](https://github.com/porscheinformatik/sonarqube-licensecheck/assets/11076541/7bcdedfd-b1db-4599-b195-599a43fe146a)

![image](https://github.com/porscheinformatik/sonarqube-licensecheck/assets/11076541/d28f4ac5-b837-4ee0-8128-2f0b880166c5)

![image](https://github.com/porscheinformatik/sonarqube-licensecheck/assets/11076541/1da2e4e5-d636-4955-bfa8-d82ab1db63fe)

**Comment by derkoe** [comment]
I have just tried this with the latest version of License Check and SonarQube 9.9.3 and cannot reproduce it.

<img width="304" alt="image" src="https://github.com/porscheinformatik/sonarqube-licensecheck/assets/123199/6e36ff63-4cde-4048-814a-2344d5e8751f">

Which version of the License Check Plugin are you running?

**Comment by jenspopp** [comment]
Hi, I'm still running 5.1.1; I will try with version 6 today and report if it fixes my issues ;-)

**Comment by jenspopp** [comment]
Thanks, with the new version 6.0.0 the issue is fixed. Works for me now
