### ISSUE TITLE
SonarQube 7.7 with the plugin 3.0.0-Beta3 - no license rules

### ISSUE THREAD

**Issue by sciffer** [porscheinformatik/sonarqube-licensecheck#41]
I installed the latest version of the plugin 3.0.0-beta3 on our SonarQube 7.7 and enabled the license scan, but could not find the license rules to enable for the license scan to work.
I ran the scan on our JS/NPM project and nothing is found(assuming the scan is not happening without those rules as mentioned in your docs) - Am I suppose to do anything in order to have those rules show up(so that I can enable them)?

**Comment by derkoe** [comment]
The rules should be there. The names are "Dependency has unknown license [license-check]" and "License is not allowed [license-check]". The rules are still under the language "Java" (even though npm is also scanned). 

We have to split this up, I have created #42

**Comment by derkoe** [comment]
@sciffer any news on this? Otherwise I will close this issue.

**Comment by sciffer** [comment]
I guess the problem is the java rules, I don’t use the java plugin.
You can close it.

Thanks,
Shalom
