### ISSUE TITLE
Split rules to language "Java" and "JavaScript"

### ISSUE THREAD

**Issue by derkoe** [porscheinformatik/sonarqube-licensecheck#42]
Currently both rules "Dependency has unknown license [license-check]" and "License is not allowed [license-check]" are under language Java even though NPM package.json is scanned. 

We have to split the rules and assign the license issues to the corresponding language.

**Comment by derhecht** [comment]
see https://github.com/porscheinformatik/sonarqube-licensecheck/issues/182
