### ISSUE TITLE
enhancement: provide metrics -> ready for quality gates

### ISSUE THREAD

**Issue by tiekuhn** [porscheinformatik/sonarqube-licensecheck#43]
Hello,

first of all: THANK you for providing this awesome plugin that really already made my life easier big time in its current state :-)!!!!

While playing around with the plugin I wanted to define a quality gate in sonar so that projects with unknown or "not allowed" licences more visibly fail.
Unfortunately I had to find out that this does not seem to be supported in this plugin.

Proposal:
* let the plugin yield 2 metrics
  * number of unknown licences
  * number of not allowed licences

With providing this 2 metrics projects could then set up corresponding Quality gates e.g. ("number of unknown licences > 0" -> fail).

This would help enforcing corresponding rules in the teams.

A similar approach is in place for e.g. 
https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin 

this plugin yields a full set of metrics that can be used in quality gates
![image](https://user-images.githubusercontent.com/4927859/56581395-2aae0d80-65d5-11e9-9f89-116fcbe66bf2.png)

*known workaround*
* the license scanner reports unknown or not allowed licences as "blockers" so one could just set up a quality gate that fails at new or >0 blockers...but thats not very specific to licencing issues as blockers could also be caused by other types of issues

Thank you very much in advance for considering this requirements

**Comment by kreutziger** [comment]
:+1:
