### ISSUE TITLE
Empty Project Dashboard in SQ7.7 & other issues with 3.0.0-beta-3

### ISSUE THREAD

**Issue by HSSE-Dev** [porscheinformatik/sonarqube-licensecheck#44]
Hello, 
we use SonarQube 7.7 and SonarQube License Check Plugin 3.0.0-beta-3 to check java licenses und dependencies. "License is not allowed", "Dependency has unknown license" is enabled.
The first problem is, that license check don't use the global license list settings and analyze only for the specific project license specification. 
![sq_license_Check_issues](https://user-images.githubusercontent.com/23707828/58313293-8276a900-7e0d-11e9-91c1-adac1d73bebe.PNG)
Do we have to update the "License Check - Maven Dependencies" for each license?
Because we only find the dependencies which are registered in "License Check - Maven Dependencies":
![grafik](https://user-images.githubusercontent.com/23707828/58313517-09c41c80-7e0e-11e9-85f8-419b17678bf9.png)

Project Dashboard Issue:
We always have an empty project dashboard, but for the same project we get dependencies issue (upperimage).
![grafik](https://user-images.githubusercontent.com/23707828/58313240-5ce99f80-7e0d-11e9-8ec8-90d72b146b39.png)

Thank for your support

**Comment by derkoe** [comment]
> Do we have to update the "License Check - Maven Dependencies" for each license?

No. Under the tab "Licenses" you can define which licenses are globally allowed in your organisation (e.g. Apache-2.0 and MIT). The default is to forbid all licenses - that's why you get those issues.

The Maven Dependencies and Maven Licences tabs are here because Maven has no structured approach to licenses (npm does with SPDX). With Maven Dependencies setting you can map Maven groupId:artifactId matching regex to a license - e.g. "org\.apache\..*" -> Apache-2.0. With the Maven Licenses setting you can map the string in the license name of the pom.xml to a license - e.g. "Apache.*2.*" -> Apache-2.0.

**Comment by derkoe** [comment]
> We always have an empty project dashboard, but for the same project we get dependencies issue 

Just tried that with 7.7 and I also get an empty dashboard. I will have a look into this.

**Comment by derkoe** [comment]
Seems like SonarQube changed some API semantics with 7.7 - measures on modules are not stored anymore. This breaks the storing of licenses/dependencies. 

Not a good practice do break APIs in minor versions `¯\_(ツ)_/¯`

See also https://github.com/SonarOpenCommunity/sonar-cxx/pull/1695

**Comment by derkoe** [comment]
This means the License Check project dashboard only works for single module projects.

**Comment by tiekuhn** [comment]
Hi @derkoe ,
does your commit reenable support for multi module projects in SQ 7.7+ or will multi module projects no longer be supported ... which would be pretty sad as we have plenty of them :-(

If it re-enables support, do you see any chance to release a new "beta" for v3 including this commit so we can try it out (cause we already are seing the issue also on our end)
THANKS

**Comment by derkoe** [comment]
#46 addresses this

**Comment by HSSE-Dev** [comment]
@derkoe Thanks for the quick help and bug fixing, we will test the release soon.
Have a nice week!
