### ISSUE TITLE
Supplied spdx_license_list.json contains data not matching the software.

### ISSUE THREAD

**Issue by pjoran** [porscheinformatik/sonarqube-licensecheck#7]
After installing this plugin I get a row in my Sonarqube database - properties table - with the prop_key = licensecheck.licenses.
The text_value contains the json data for licenses, but the format does not seem to match what the plugin expects.
The data contains the 'osiApproved' property while the software seems to use 'status'.
In addition, the value in the database is interpreted as boolean as there is no double-qoutes in the data file. The program is expecting String not Boolean when parsing the json data from the database.
This causes an exception in the plugin when trying to display the licenses.

**Comment by derkoe** [comment]
Could you provide the exception? Which SonarQube version are you using? Which plugin version?

**Comment by pjoran** [comment]
Unfortunately I don't have that exception anymore.
I used version 1.0.1.
However, I see that you have changed the json file now to match what I was using when it finally worked.
Thanks!
