### ISSUE TITLE
Configuration, filter for open and  closed license type

### ISSUE THREAD

**Issue by rebse** [porscheinformatik/sonarqube-licensecheck#79]
Thanks for the plugin.
At a first glance i’m missing some filter for open and closed licenses.
Not everyone has a juristic background and in corporate environment you shouldn’t use a license that obliges to open source your code.

**Comment by derkoe** [comment]
There is no such thing as "open" and "closed" licenses - each license has its own subtlety. 

Every company may have other policies regarding licenses and should set which licenses are allowed/disallowed.
