### ISSUE TITLE
Licenses are not scanned correctly if Maven execution has `-B` or `--batch-mode` flag

### ISSUE THREAD

**Issue by oliverlockwood** [porscheinformatik/sonarqube-licensecheck#80]
Through much trial and error, I have discovered that licenses aren't scanned correctly (you just get licenses used by the first submodule) if you run Maven in batch mode e.g. `mvn -B sonar:sonar` instead of just `mvn sonar:sonar`.

This may have been the issue that was affecting people in tickets #34, #72.

I hope to find some time next week to look into the plugin code to see if it's something that can easily be fixed.  If so I'll raise a PR to that effect; if not I'll raise a PR to note this in the documentation.  In the meantime, I thought raising this issue might help others.

**Comment by derkoe** [comment]
Yes, there are dependencies missing when scanning with batch mode and version 2.0.1 (for me it was missing the last submodule). This seems very strange - I'll have a look at that. 

This could be fixed with 3.x but I'll have to verify that.

**Comment by derkoe** [comment]
Just tried the same project with batch mode again (under Windows) and it has all dependencies - mhmmmm.

**Comment by derkoe** [comment]
@oliverlockwood do you also see this in your logs?

    [WARNING] 11:37:02.518 Could not get dependency list via maven

**Comment by oliverlockwood** [comment]
@derkoe yes, I see that warning in the batch-mode logs only.

**Comment by derkoe** [comment]
I found the issue - the problem with multi-module projects is that the plugin runs a `mvn dependency:list` for each module. When you have inter-module dependencies (which is almost always the case), then the current (SNAPSHOT) version may not be in the local or a remote repository. That results in a failing `dependency:list` with something like: 

    Failed to execute goal on project module3: Could not resolve dependencies for project group.id:module2:jar:0.0.1-SNAPSHOT

The solution is to do a `mvn install` before the SonarQube analysis:

    mvn -B -Dmaven.test.failure.ignore org.jacoco:jacoco-maven-plugin:prepare-agent install
    mvn -B sonar:sonar

**Comment by derkoe** [comment]
Will add the Maven execution log errors as warning - so that one can see what the original problem was.

**Comment by derkoe** [comment]
I created a pre-release [3.1.0-rc-1](https://github.com/porscheinformatik/sonarqube-licensecheck/releases/tag/v3.1.0-rc-1) that includes the error log
