### ISSUE TITLE
Possibility to add ECCN information.

### ISSUE THREAD

**Issue by pjoran** [porscheinformatik/sonarqube-licensecheck#9]
Along with the license information for a package we need to consider its ECCN classification.
Would it make sense to add support for this in the licensecheck plugin?
At least add a field when mapping maven dependencies?
Thanks!

By the way , great plugin! :-)

**Comment by derkoe** [comment]
I never heard of ECCN before, after searching for it I have to say poor Americans :)

Anyway I guess it won't make a lot of sense since moste licenses are read automatically (especially all NPM packages). So there's no way to set a number per library.
