### ISSUE TITLE
Did "Using transporter WagonTransporter" work?

### ISSUE THREAD

**Issue by Janpopan** [porscheinformatik/sonarqube-licensecheck#90]
During the build stage Using transporter WagonTransporter works fine for us.
But it did not work for the licesencheck for me. 

XXXXXX are replacements for internals.

`build	01-Aug-2019 16:23:45	[WARNING] 16:23:45.850 Could not get dependency list via maven
build	01-Aug-2019 16:23:45	[WARNING] 16:23:45.850 [ERROR] Some problems were encountered while processing the POMs:
build	01-Aug-2019 16:23:45	The build could not read 1 project -> [Help 1]
build	01-Aug-2019 16:23:45	  
build	01-Aug-2019 16:23:45	  The project XXXXXXXX (C:\XXXXXXX\services\pom.xml) has 1 error
build	01-Aug-2019 16:23:45	    Non-resolvable parent POM for XXXXXXXX: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.1.3.RELEASE from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and 'parent.relativePath' points at wrong local POM @ XXXXXXXXXX, C:\XXXXXXXX\source\pom.xml, line 6, column 13 -> [Help 2]
build	01-Aug-2019 16:23:45	
build	01-Aug-2019 16:23:45	To see the full stack trace of the errors, re-run Maven with the -e switch.
build	01-Aug-2019 16:23:45	Re-run Maven using the -X switch to enable full debug logging.
build	01-Aug-2019 16:23:45	
build	01-Aug-2019 16:23:45	For more information about the errors and possible solutions, please read the following articles:
build	01-Aug-2019 16:23:45	[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
build	01-Aug-2019 16:23:45	[Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
build	01-Aug-2019 16:23:45	
build	01-Aug-2019 16:23:45	[DEBUG] 16:23:45.866 Saving depenencies for module [key=XXXXXXXXXXXXXX]: []
build	01-Aug-2019 16:23:45	[DEBUG] 16:23:45.866 Saving licenses for module [key=XXXXXXXXXXX]: []
build	01-Aug-2019 16:23:45	[INFO] 16:23:45.866 Sensor License Check [licensecheck] (done) | time=2706ms`

**Comment by derkoe** [comment]
I'm not sure what your problem is exactly. 

The error above indicates that you have MITM proxy in your setup and that you'll need to add it's Root CA to the cacerts in the JVM you are using. But this is a general Maven problem.
See also https://stackoverflow.com/questions/25911623/problems-using-maven-and-ssl-behind-proxy/25912982#25912982

**Comment by Janpopan** [comment]
We havn't a proxy, we have to use a local mirror.
And so we use a settings.xml like [https://stackoverflow.com/questions/21252800/how-to-tell-maven-to-disregard-ssl-errors-and-trusting-all-certs/21266642#21266642](https://stackoverflow.com/questions/21252800/how-to-tell-maven-to-disregard-ssl-errors-and-trusting-all-certs/21266642#21266642) 
This works perfect during the install stage, but this seems to be ignored during the sonar stage (at least for https).

**Comment by derkoe** [comment]
So, you are adding `-Djavax.net.ssl.trustStore=` to every Maven command?

**Comment by Janpopan** [comment]
We use bamboo and sonar, so this kind of paramters are generated or configurated for the maven call
`"org.codehaus.plexus.classworlds.launcher.Launcher -Djava.io.tmpdir=C:\\Users\\sys-sbuild\\AppData\\Local\\Temp\\foo sonar:sonar -Dsonar.projectVersion=1.4.0 -Dmaven.repo.local=C:\\foo/m2_repo -Djavax.net.ssl.trustStore=c:\\foo\\barStore.jks -Djava.io.tmpdir=C:\\foo/temp -B -X -s C:\\foo/source/settings.xml -Dsonar.host.url=https://test-sonar.foo.bar -Dsonar.login=****** -Dsonar.password=******";`

with this parameters your maven commandline parser ends with a NPE.
Because you only expect -s or -gs right?

**Comment by Janpopan** [comment]
MavenDependencyScanner

Line 316

cmd = parser.parse(options, commandArgs.split(" "));
->
cmd = parser.parse(options, commandArgs.split(" "), true);

**Comment by Janpopan** [comment]
I found a solutions here:
[https://stackoverflow.com/questions/6049470/can-apache-commons-cli-options-parser-ignore-unknown-command-line-options](https://stackoverflow.com/questions/6049470/can-apache-commons-cli-options-parser-ignore-unknown-command-line-options)

the third example did the trick. The parser ignores unknown options from the cli and did break up.
